---
# Palybook for deploying the container
- name: Deploy
  hosts: tag_Name_Workers 
  become: true
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
        state: present
      become: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
      become: yes

    - name: Giving permission
      command: sudo chmod 666 /var/run/docker.sock

    - name: Docker Login
      docker_login:
        username: vizzwastaken
        password: 123456789
        reauthorize: yes

    - name: Pull the container
      docker_image:
        name: vizzwastaken/project:scalc
        source: pull

    - name: Run a Docker Container Interactively
      docker_container:
        name: my_container
        image: vizzwastaken/project:scalc  # Replace with your Docker image and tag
        state: started
        ports:
          - "80:80"
