name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Basic-Quality-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3

      - name: check if Docker File exists
        run: |
          ls -lrt
          echo ${{ github.event.repository.name }}
          if [ -f ./Dockerfile ]; then
            echo "====================================="
            echo "        Docker file exists"
            echo "====================================="
          else
            echo "====================================="
            echo "      Docker file dosent exist"
            echo "====================================="
            exit 1
          fi    

      - name: Linting source code
        uses: github/super-linter@v4
        env:
           VALIDATE_ALL_CODEBASE: true
           DEFAULT_BRANCH: master
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           VALIDATE_PYTHON3: true
           VALIDATE_MARKDOWN: false
           VALIDATE_GITHUB_ACTIONS: false
           
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: vizzwastaken
          password: ${{ secrets.DOCKER_PASS }}
          
  Push-Docker-Image:
    needs: [Basic-Quality-Checks]
    runs-on: ubuntu-latest
    steps:        
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: vizzwastaken
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vizzwastaken/demo:latest
        
  Deploy-Ansible-Playbook:
    needs: [Push-Docker-Image]
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Pull
        uses: docker/build-push-action@v4
        with:
          pull: true
          tags: vizzwastaken/demo:latest
        
      - name: Install Ansible
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt install ansible
        
      - name: Add SSH key and known_hosts for EC2 instance
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.IP_ADDR }} >> ~/.ssh/known_hosts

#       - name: Install SSH key
#         uses: shimataro/ssh-key-action@v2
#         with:
#             key: ${{ secrets.SSH_KEY }}
#             known_hosts: unnecessary
            
#       - name: Copy Ssh-key
#         run: |
#           ssh-agent bash
#           chmod 600 /home/runner/.ssh
#           ssh-add /home/runner/.ssh/key.pem
          
      - name: Add Inventory File
        run: |
          sudo sh -c "echo [servers] > /etc/ansible/hosts"
          sudo sh -c "echo ${{ secrets.IP_ADDR }} >> /etc/ansible/hosts"
          sudo cat /etc/ansible/hosts

          
      - name: Run Playbook
        run: ansible-playbook masterplaybook.yaml --extra-vars pass=${{ secrets.DOCKER_PASS }}
        

          
          
    
    

