name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Basic-Quality-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3

      - name: check if Docker File exists
        run: |
          ls -lrt
          echo ${{ github.event.repository.name }}
          if [ -f /${{ github.event.repository.name }}/Dockerfile ]; then
            echo "====================================="
            echo "        Docker file exists"
            echo "====================================="
          else
            echo "====================================="
            echo "      Docker file dosent exist"
            echo "====================================="
          fi    

#       - name: Linting source code
#         uses: github/super-linter@v4
#         env:
#           VALIDATE_ALL_CODEBASE: false
#           DEFAULT_BRANCH: master
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           VALIDATE_PYTHON3: true

