name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  REMOTE_HOST: ip-172-31-89-254.ec2.internal
  REMOTE_USER: ubuntu

jobs:
  Basic-Quality-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files
        uses: actions/checkout@v3

      - name: check if Docker File exists
        run: |
          ls -lrt
          echo ${{ github.event.repository.name }}
          if [ -f ./Dockerfile ]; then
            echo "====================================="
            echo "        Docker file exists"
            echo "====================================="
          else
            echo "====================================="
            echo "      Docker file dosent exist"
            echo "====================================="
            exit 1
          fi    

      - name: Linting source code
        uses: github/super-linter@v4
        env:
           VALIDATE_ALL_CODEBASE: true
           DEFAULT_BRANCH: master
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           VALIDATE_PYTHON3: true
           VALIDATE_MARKDOWN: false
           VALIDATE_GITHUB_ACTIONS: false
           
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: vizzwastaken
          password: ${{ secrets.DOCKER_PASS }}
          
  Push-Docker-Image:
    needs: [Basic-Quality-Checks]
    runs-on: ubuntu-latest
    steps:        
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: vizzwastaken
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vizzwastaken/demo:latest

  Conenct-To-Host:
    needs: [Push-Docker-Image]
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Copy Ansible playbook
        uses: appleboy/scp-action@master
        with:
          host: 34.238.115.106
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          

      - name: SSH
        run: |
          ls
          echo "${{ secrets.SSH_KEY }}" >> key.pem
          ssh -i key.pem ubuntu@ec2-34-238-115-106.compute-1.amazonaws.com

      # - name: Run Ansible playbook
      #   run: |
      #      ls 
      #      ansible-playbook masterplaybook.yaml 
        
  # Deploy-Ansible-Playbook:
  #   needs: [Push-Docker-Image]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v3
        
  #     - name: Pull
  #       uses: docker/build-push-action@v4
  #       with:
  #         pull: true
  #         tags: vizzwastaken/demo:latest
        
  #     # - name: Install Ansible
  #     #   run: |
  #     #     sudo apt-add-repository ppa:ansible/ansible
  #     #     sudo apt update
  #     #     sudo apt install ansible
        

  #     # - name: Install SSH key
  #     #   uses: shimataro/ssh-key-action@v2
  #     #   with:
  #     #       key: ${{ secrets.SSH_KEY }}
  #     #       known_hosts: ${{ secrets.KNOWN_HOST }}
            
          
  #     # - name: Add Inventory File
  #     #   run: |
  #     #     sudo sh -c "echo [servers] > /etc/ansible/hosts"
  #     #     sudo sh -c "echo 34.238.115.106 >> /etc/ansible/hosts"
  #     #     sudo cat /etc/ansible/hosts
        
  #     # - name: disbale hostkey
  #     #   run: export ANSIBLE_HOST_KEY_CHECKING=False

          
  #     - name: Run Playbook
  #       run: ansible-playbook masterplaybook.yaml --extra-vars pass=${{ secrets.DOCKER_PASS }}
        

          
          
    
    

